### PR TITLE
Display Tweet's time

### PR DESCRIPTION
**Pull request by chaspy**
close: https://github.com/chaspy/favsearch/issues/44

### CODE REVIEW

**Comment by chaspy** [comment]
👀 ? http://favsearch-pr-48.herokuapp.com

**Comment by chaspy** [comment]
need https://github.com/chaspy/favsearch/commit/51c974c0cb5901548cda753374e32f9528d47071 😢

**Comment by kamontia** [comment]
@chaspy Please rebase and resolve conflicts.

**Comment by chaspy** [comment]
@kamontia 
resolved. please review and merge
👀 https://favsearch-pr-48.herokuapp.com

**Comment by kamontia** [comment]
@chaspy Thank you for the implementation of feedback.

**Pull request merged**
