### PR TITLE
Uppercase and lowercase are not distinguished to search tweet's text

### PR DESCRIPTION
**Pull request by chaspy**
ref: https://github.com/chaspy/favsearch/issues/40

ref(toLowerCase): https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase

### CODE REVIEW

**Comment by chaspy** [comment]
@kamontia 
Should we do the same thing with Twitter's name and ID as this PR?
What do you think?

**Comment by chaspy** [comment]
hi! @kamontia I resolved confilict
please review!
Do you think that TwitterID and (screan)name should not distinguish between uppercase and lowercase letters?

**Comment by chaspy** [comment]
👀 https://favsearch-pr-49.herokuapp.com

**Comment by kamontia** [comment]
@chaspy I suppose that searching method should be unified, so TwitterID and screen name also should be searched with no-case-sensitive.

**Comment by chaspy** [comment]
@kamontia 
please review and merge

**Comment by kamontia** [comment]
@chaspy Thank you for quick work

**Pull request merged**
